"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*v^&^7afe@jia72_bmcma$ra@t(ufjm9(8*&2bu4dp-$6qohbk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',
    'accounts',
    'foodstore',
    'carts',
    'orders',
    'storages'


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_EXPIRE_SECONDS = 3600  # 1 hour
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = 'accounts/login'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


ROOT_URLCONF = 'djangoProject.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.menu_links',
                'carts.context_processor.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'
AUTH_USER_MODEL = 'accounts.Account'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


#Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/eb status
# aws_access_key_id = 'ASIATUYJP7SUPOMLYSOH'
# aws_secret_access_key = 'Jy+yPXiuRHu2kYi1Nw9sPDM1aKeP2cRvMi+/eBbp'
# aws_session_token = 'IQoJb3JpZ2luX2VjEKL//////////wEaCXVzLWVhc3QtMSJGMEQCICJrrGbYq+4p6vx1xleJVIMiaD0JsI+ZEb2NsHsDQyNbAiBcmDJRn31WaD+lBaU4XWU9qphQ4Hn8ASo+BJLsu0LuWir7AwgaEAMaDDI1MDczODYzNzk5MiIMMNIfXFXlUlmQ6vtsKtgD8JuCgJ1wNp70FIhzXHYBfrWEesJtrGoYxm8+jxitT52v9IPBC3abxGHpBtUEMRaFtyjT/43s/9ATrd7Flq2AOXt0th6ECOVNkQQO21VviZNgCDoomdoabYOHaSHa4Lx0dDHOIIhgDzJ5J5gjpzpoci5TRW86uro1u/FE5+BMUOLeEC6DDHNG3MQqyguPHM/TGnX572wmK3JvQd1HiCxbzd5FdKd4Q3lqd6HrvPctqKTTTlK3LAwR2UpgNk0PFCUBUPhF0yXZebNytZefMx2qBjG0q2gt5LqWofUBF4IVQpEfNUE+AN1ajOpDgbp3dqbizTxR0RGZeDpWWhj2zvLqF4Xgh/Z8gpwPBUNIRPvSCwao4OehIiGOtOvfjod/bpQocjsk8O62OxsYlagE037PKq3Ato8ltvSu06lfzEVY904Gb4pSWCuNaN1z9sEvR5PU+wv2unO7Mgl/4g9TScvO7OTf61tG62MCCCHL/lqQOBuEI190ImkRz7MuKhShTOuWAU0+won+0ryHU8gkkLmSjnjkSmetJ3eNO83V7gJmdGZVMWIaF/2ka8ARLZmneCNWy2DGsxyZG7Ig/kZWfJYHTXSWJi8Ca9A6eDDKvddc9+TgW1QeXxWHIDDqhN2rBjqnAeUm5JviWUttVUZjKIo4qMPhu8mLGvpadW3n8l9DOfAxRGhT43nSzuJI7gQKHL8bUTWSJ8auSk/lR6v/Yo7tugBADqRo5M5LbfDhZwHEwr6cusaKp2slwwRcrsFQoFYjdtvCxiB32mROCM9kzirshYUduUUdOGcQQPwP8a9ofI2aXFYZnFAhaTGNN5C7u50OTbICzhT2LcNGoO4rH9R9G5CQFauO0z5a'
# aws_storage_bucket_name = 'x22184805-hunger-management'
# aws_s3_custom_domain = '%s.s3.amazonaws.com' % aws_storage_bucket_name
# aws_s3_object_parameters = {
#     'CacheControl': 'max-age=86400',
# }
# aws_s3_file_overwrite = False
# aws_default_acl = 'public-read'
# aws_location = 'static'
#
# STATICFILES_DIRS = [
#     'djangoProject/static',
# ]
# STATIC_URL = 'https://%s/%s/' % (aws_storage_bucket_name, aws_location)
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# DEFAULT_FILE_STORAGE = 'djangoProject.media_storages.MediaStorage'
#
# # media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'djangoProject', 'static'),
]


# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = (os.path.join('djangoProject', 'static'),)
# django_heroku.settings((locals()))
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field





MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
