# Generated by Django 4.2.6 on 2023-10-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0002_rename_is_avaliable_product_is_availible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availible',
            new_name='is_available',
        ),
    ]
