# Generated by Django 4.2.6 on 2023-11-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0003_rename_is_availible_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
