name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

    - name: Update Heroku CLI
      run: |
        wget https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
        tar -xvzf heroku.tar.gz
        sudo mv heroku-cli-* /usr/local/lib/heroku
        export PATH="/usr/local/lib/heroku/bin:$PATH"
        heroku --version

        # Set Heroku API key
        echo -n $HEROKU_API_KEY > ~/.netrc
        chmod 600 ~/.netrc

        # Add Heroku remote
        heroku git:remote -a hunger-manager-management

        # Push to Heroku
        git push heroku main